"""Alignment check (build-failing): the five takeaways must come from one source and read the same everywhere.

Source level: the main abstract, the main takeaway list, the claims table, the conclusion, the supplement summary and
the supplement's at-a-glance table all use the \\Tk<Key>Title/Head/Label macros generated by build_assets.py.
Rendered level: the five titles appear, in order, in the main abstract page and the supplement summary page, and each
headline number appears on both pages; each title appears at least four times in the main paper (abstract, list,
claims table, conclusion) and twice in the supplement (summary, at-a-glance table)."""
from __future__ import annotations

import json
import re
import subprocess
import sys
from pathlib import Path

HERE = Path(__file__).resolve().parent
MAINPDF, SUPPPDF = HERE / "decision-model-fit-v5.pdf", HERE / "decision-model-fit-v5-supplement.pdf"
KEYS = ["One", "Two", "Three", "Four", "Five"]
MACROS = {}
for f in ("generated/numbers.tex", "generated/jb/numbers.tex"):
    t = (HERE / f).read_text()
    for m in re.finditer(r"\\newcommand\{\\(\w+)\}\{", t):
        i, depth = m.end(), 1
        while depth:
            depth += {"{": 1, "}": -1}.get(t[i], 0)
            i += 1
        MACROS[m.group(1)] = t[m.end():i - 1]


def render(s: str, depth: int = 0) -> str:
    """Approximate the printed text of a macro value."""
    if depth > 8:
        return s
    s = re.sub(r"\\(\w+)", lambda m: render(MACROS[m.group(1)], depth + 1) if m.group(1) in MACROS else m.group(0), s)
    for a, b in ((r"\X", "×"), (r"\,\%", "%"), (r"\%", "%"), (r"\$", "$"), ("{,}", ","), ("--", "–"), ("$-$", "−"),
                 (r"\,", ""), ("\\ ", " "), ("~", " ")):
        s = s.replace(a, b)
    s = re.sub(r"\\[a-zA-Z]+", "", s)
    return " ".join(s.replace("{", "").replace("}", "").split())


def norm(t: str) -> str:
    t = re.sub(r"-\n", "", t)
    return " ".join(t.replace("\u00ad", "").split())


def page_text(pdf: Path, first: int, last: int) -> str:
    return norm(subprocess.run(["pdftotext", "-f", str(first), "-l", str(last), str(pdf), "-"],
                               capture_output=True, text=True, check=True).stdout)


fails = []
for _f in ("sections/m0-abstract.tex", "supp/summary.tex"):
    if "\\input{sections/abstract-body}" not in (HERE / _f).read_text():
        fails.append(f"{_f} does not input the shared abstract")
# ---- source level
SRC = {"main abstract": ("sections/abstract-body.tex", "THL"), "main takeaway list": ("sections/m1-intro.tex", "TL"),
       "claims table": ("sections/m1b-claims.tex", "TL"), "conclusion": ("sections/m9-limits.tex", "THL"),
       "supplement summary": ("sections/abstract-body.tex", "THL"), "at-a-glance table": ("generated/tables/takeaways-glance.tex", "THL")}
for name, (f, need) in SRC.items():
    t = (HERE / f).read_text()
    for kind, mac in (("T", "Title"), ("H", "Head"), ("L", "Label")):
        if kind not in need:
            continue
        pos = [t.find(f"\\Tk{mac}{{{k}}}") for k in KEYS]
        if min(pos) < 0:
            fails.append(f"{name}: missing \\Tk{mac}{{...}} for " + ", ".join(k for k, p in zip(KEYS, pos) if p < 0))
        elif pos != sorted(pos):
            fails.append(f"{name}: \\Tk{mac} macros out of order")
takeaways = json.loads((HERE / "generated/takeaways.json").read_text())
if [x["key"] for x in takeaways] != KEYS:
    fails.append("generated/takeaways.json keys differ from the expected five")
# ---- rendered level
titles = {k: render(MACROS[f"Tk{k}Title"]) for k in KEYS}
heads = {k: render(MACROS[f"Tk{k}Head"]) for k in KEYS}
labels = {k: render(MACROS[f"Tk{k}Label"]) for k in KEYS}
main_all, supp_all = page_text(MAINPDF, 1, 999), page_text(SUPPPDF, 1, 999)
for doc, first_page, minimum, alltext in (("main paper", page_text(MAINPDF, 1, 1), 4, main_all),
                                          ("supplement", page_text(SUPPPDF, 1, 1), 2, supp_all)):
    pos = []
    for k in KEYS:
        p = first_page.find(titles[k])
        pos.append(p)
        if p < 0:
            fails.append(f"{doc} abstract/summary page: title {k} not rendered: {titles[k]!r}")
        for num in re.findall(r"\d[\d,.]*\d|\d", heads[k]):
            if num not in first_page:
                fails.append(f"{doc} abstract/summary page: headline number {num} of takeaway {k} missing")
        if f"[{labels[k]}]" not in first_page:
            fails.append(f"{doc} abstract/summary page: strength label of takeaway {k} missing: [{labels[k]}]")
        n = alltext.count(titles[k])
        if n < minimum:
            fails.append(f"{doc}: title {k} rendered {n} times, expected at least {minimum}")
    if all(p >= 0 for p in pos) and pos != sorted(pos):
        fails.append(f"{doc} abstract/summary page: takeaways out of order")
    print(f"alignment: {doc}: 5 titles, {sum(len(re.findall(r'[0-9][0-9,.]*[0-9]|[0-9]', heads[k])) for k in KEYS)} headline numbers, 5 labels checked")
for f in fails:
    print("FAIL:", f)
print("alignment OK" if not fails else f"alignment: {len(fails)} failure(s)")
sys.exit(1 if fails else 0)
